# -*- coding: utf-8 -*-
"""challenge 02-03.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BCAWXRRXNM50QG9VqNR_XbsZCx7DerIP
"""

count = 1
mutiplier = 1
spaces = " "
print("     1    2    3    4    5    6    7    8    9    10")
for i in range(1,11):
  if(i < 10):
    print(i, end = spaces * 4)
  else:
    print(i, end = spaces * 3)
  for z in range(1,11):
    if(z*i < 10):
      print(z * i,end = spaces * 4)
    else:
      print(z * i,end = spaces * 3)
  print()