# -*- coding: utf-8 -*-
"""challenge 02-04.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pl-jc4CoNNaVWamQlDE0TSBK_pJ-X2xy
"""

listOne = [1, 2, 3, 4, 5]
listTwo = [4, 5, 6, 7, 8, 9]
shared = []

for i in listOne:
  for z in listTwo:
    if(i == z):
      shared.append(i)

print(shared)