# -*- coding: utf-8 -*-
"""challenge 02-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4bswe_iX1ZNRCZ90efR56_gd30Qq1ZO
"""

inventory = {'Apple': 10, 'Banana': 1, 'Orange': 7}
purchased_items = ['Apple', 'Banana', 'Apple', 'Orange', 'Banana']

for i in purchased_items:
  if(inventory[i] != 0):
    inventory[i] = inventory[i] - 1
  else:
    print(i + " is not in the inventory")
print(inventory)