# -*- coding: utf-8 -*-
"""challenge 02-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3GDziThmRZhg-F4o8zIlhPXfXMy0ln-
"""

grades = {'Alice': 85, 'Bob': 60, 'Cathy': 90}

for i in grades:
  if(grades[i] >= 90):
    grades[i] = "A"
  elif(grades[i] >= 80):
    grades[i] = "B"
  elif(grades[i] >= 70):
    grades[i] = "C"
  else:
    grades[i] = "F"

print(grades)